version: '3.4'

services:
  mearnstackbackend:
    image: mearnstackbackend
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
